const axios = require('axios');

/**
 * Email Service for sending meeting summaries via Brevo API
 * Port 443 (HTTPS) is not blocked by Render free tier.
 */

const sendSummaryEmail = async (recipientEmail, meetingTitle, summary, timestamp) => {
    try {
        console.log('[EmailService] Attempting to send summary via Brevo API...');
        const apiKey = process.env.BREVO_API_KEY?.trim();
        const senderEmail = (process.env.SENDER_EMAIL || process.env.EMAIL_USER)?.trim();

        if (!apiKey) {
            console.error('[EmailService] Error: BREVO_API_KEY is missing!');
            throw new Error('BREVO_API_KEY is not defined in environment variables');
        }

        console.log('[EmailService] Using sender:', senderEmail);
        console.log('[EmailService] Recipient:', recipientEmail);

        // Parse summary text to handle basic markdown-like formatting for the email
        const formattedSummary = summary
            .replace(/^#+ (.*$)/gm, '<h2 style="color: #f97316; font-size: 18px; margin-top: 20px; margin-bottom: 8px; border-bottom: 1px solid #eee; padding-bottom: 4px;">$1</h2>')
            .replace(/\*\*(.*?)\*\*/g, '<strong style="color: #1f2937;">$1</strong>')
            .replace(/\n\n/g, '<div style="margin-bottom: 12px;"></div>')
            .replace(/\n/g, '<br>');

        // HTML email template
        const htmlContent = `
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="UTF-8">
                <style>
                    body {
                        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                        line-height: 1.6;
                        color: #1f2937;
                        background-color: #f3f4f6;
                        margin: 0;
                        padding: 20px;
                    }
                    .email-container {
                        max-width: 700px;
                        margin: 0 auto;
                        background-color: #ffffff;
                        padding: 40px;
                        border-radius: 8px;
                        box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
                    }
                    .main-title {
                        color: #f97316;
                        font-size: 28px;
                        font-weight: 800;
                        margin: 0 0 15px 0;
                        line-height: 1.2;
                    }
                    .divider {
                        height: 1px;
                        background-color: #e5e7eb;
                        margin-bottom: 30px;
                    }
                    .summary-content {
                        font-size: 15px;
                        color: #374151;
                    }
                    .footer {
                        margin-top: 40px;
                        padding-top: 20px;
                        border-top: 1px solid #f3f4f6;
                        text-align: center;
                        font-size: 11px;
                        color: #9ca3af;
                    }
                </style>
            </head>
            <body>
                <div class="email-container">
                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
                        <tr>
                            <td align="left" style="padding-bottom: 25px; border-bottom: 2px solid #f97316;">
                                <div style="display: flex; align-items: center; gap: 8px;">
                                    <span style="color: #f97316; font-size: 22px; font-weight: 800; letter-spacing: -0.5px;">MeetSummary</span>
                                </div>
                                <div style="color: #6b7280; font-size: 11px; margin-top: 3px; font-style: italic;">AI Meeting Assistant</div>
                            </td>
                            <td align="right" style="padding-bottom: 25px; border-bottom: 2px solid #f97316;">
                                <span style="color: #6b7280; font-size: 11px; font-weight: 500;">${timestamp}</span>
                            </td>
                        </tr>
                    </table>

                    <h1 class="main-title">${meetingTitle}</h1>
                    
                    <div class="divider"></div>

                    <div class="summary-content">
                        ${formattedSummary}
                    </div>

                    <div class="footer">
                        <p>Generated by <strong>MeetSummary</strong> • AI Meeting Assistant</p>
                        <p>© ${new Date().getFullYear()} MeetSummary. All rights reserved.</p>
                    </div>
                </div>
            </body>
            </html>
        `;

        const payload = {
            sender: { name: "MeetSummary", email: senderEmail },
            to: [{ email: recipientEmail }],
            subject: `Meeting Summary: ${meetingTitle}`,
            htmlContent: htmlContent,
            textContent: `${meetingTitle}\n\nGenerated on ${timestamp}\n\n${summary}\n\n---\nThis summary was generated by MeetSummary`
        };

        const response = await axios.post('https://api.brevo.com/v3/smtp/email', payload, {
            headers: {
                'api-key': apiKey,
                'Content-Type': 'application/json'
            }
        });

        console.log('[Backend - Email] Message sent successfully via Brevo:', response.data.messageId);
        return { success: true, messageId: response.data.messageId };

    } catch (error) {
        const errorMessage = error.response?.data?.message || error.message;
        console.error('[Backend - Email] Error sending email via Brevo:', errorMessage);
        throw new Error('Failed to send email: ' + errorMessage);
    }
};

module.exports = { sendSummaryEmail };
