const nodemailer = require('nodemailer');

/**
 * Email Service for sending meeting summaries
 */

// Create transporter (using Gmail as example - can be configured for other services)
const createTransporter = () => {
    // For development, you can use a service like Gmail
    // For production, use a proper email service like SendGrid, AWS SES, etc.

    return nodemailer.createTransport({
        service: 'gmail',
        auth: {
            user: process.env.EMAIL_USER,
            pass: process.env.EMAIL_PASSWORD // Use App Password for Gmail
        }
    });
};

const sendSummaryEmail = async (recipientEmail, meetingTitle, summary, timestamp) => {
    try {
        const transporter = createTransporter();

        // Parse summary text to handle basic markdown-like formatting for the email
        const formattedSummary = summary
            .replace(/^# (.*$)/gm, '<h2 style="color: #a855f7; font-size: 20px; margin-top: 25px; margin-bottom: 10px; border-bottom: 1px solid #eee; padding-bottom: 5px;">$1</h2>')
            .replace(/\*\*(.*?)\*\*/g, '<strong style="color: #4b5563;">$1</strong>')
            .replace(/\n\n/g, '<div style="margin-bottom: 15px;"></div>')
            .replace(/\n/g, '<br>');

        // HTML email template
        const htmlContent = `
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="UTF-8">
                <style>
                    body {
                        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                        line-height: 1.6;
                        color: #1f2937;
                        background-color: #f3f4f6;
                        margin: 0;
                        padding: 20px;
                    }
                    .email-container {
                        max-width: 700px;
                        margin: 0 auto;
                        background-color: #ffffff;
                        padding: 40px;
                        border-radius: 8px;
                        box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
                    }
                    .top-bar {
                        display: flex;
                        justify-content: space-between;
                        align-items: center;
                        margin-bottom: 30px;
                    }
                    .logo {
                        color: #6366f1;
                        font-size: 18px;
                        font-weight: bold;
                        text-decoration: none;
                    }
                    .timestamp {
                        color: #6b7280;
                        font-size: 11px;
                        text-align: right;
                    }
                    .main-title {
                        color: #a855f7;
                        font-size: 28px;
                        font-weight: 800;
                        margin: 0 0 15px 0;
                        line-height: 1.2;
                    }
                    .divider {
                        height: 1px;
                        background-color: #e5e7eb;
                        margin-bottom: 30px;
                    }
                    .summary-content {
                        font-size: 15px;
                        color: #374151;
                    }
                    .footer {
                        margin-top: 40px;
                        padding-top: 20px;
                        border-top: 1px solid #f3f4f6;
                        text-align: center;
                        font-size: 11px;
                        color: #9ca3af;
                    }
                </style>
            </head>
            <body>
                <div class="email-container">
                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
                        <tr>
                            <td align="left" style="padding-bottom: 20px;">
                                <span style="color: #6366f1; font-size: 16px; font-weight: bold;">MeetSummary</span>
                            </td>
                            <td align="right" style="padding-bottom: 20px;">
                                <span style="color: #6b7280; font-size: 11px;">${timestamp}</span>
                            </td>
                        </tr>
                    </table>

                    <h1 class="main-title">${meetingTitle}</h1>
                    
                    <div class="divider"></div>

                    <div class="summary-content">
                        ${formattedSummary}
                    </div>

                    <div class="footer">
                        <p>Generated by <strong>MeetSummary</strong> • AI Meeting Assistant</p>
                        <p>© ${new Date().getFullYear()} MeetSummary. All rights reserved.</p>
                    </div>
                </div>
            </body>
            </html>
        `;

        const mailOptions = {
            from: `"MeetSummary" <${process.env.EMAIL_USER}>`,
            to: recipientEmail,
            subject: `Meeting Summary: ${meetingTitle}`,
            html: htmlContent,
            text: `${meetingTitle}\n\nGenerated on ${timestamp}\n\n${summary}\n\n---\nThis summary was generated by MeetSummary`
        };

        const info = await transporter.sendMail(mailOptions);
        console.log('[Backend - Email] Message sent: %s', info.messageId);
        return { success: true, messageId: info.messageId };

    } catch (error) {
        console.error('[Backend - Email] Error sending email:', error.message);
        throw new Error('Failed to send email: ' + error.message);
    }
};

module.exports = { sendSummaryEmail };
